version: "2"

services:

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    hostname: appstack-rabbitmq
    container_name: "apprabbitmq"
    environment:
     - RABBITMQ_USERNAME=appstack 
     - RABBITMQ_PASSWORD=appstack
    ports:
     - 15672:15672
     - 5672:5672
    networks:
     - appstack
    volumes:
     - /var/lib/rabbitmq:/bitnami/rabbitmq
 
  oneview-app:
    build: .
    image: node-app:latest
    hostname: appstack-oneview 
    container_name: "appnode"
    command: node index.js
    ports:
     - "4000:4000"
    networks:
     - appstack

networks:
  appstack:
    driver: bridge

